### ISSUE TITLE
Docker support 

### ISSUE THREAD

**Issue by jasmeralia** [Bombg/SassBot#12]
I've been maintaining my own repo for Dockerizing this, and would love to raise up a PR with the GHA which will publish the Docker bits to GHCR. Each merge to master would cut a new tag and then push the new image into GHCR. Would you be amenable to that?

**Comment by Bombg** [comment]
I like it. I don't have much familiarity with Docker nor GHA/GHCR so it would be a learning opportunity. That and I have thought about adding docker support in the past.
