### ISSUE TITLE
Platform specific channels feature request 

### ISSUE THREAD

**Issue by stormerider** [Bombg/SassBot#3]
First off, thanks for this excellent application, it's very helpful!

It would be really convenient if we could specify different channels for different platforms. In our Discord, we have one channel for twitch (and other SFW streaming sites like Kick). We have a different channel (flagged with the Disvord NSFW indicator) that we post mfc/cb/onlyfans/fansly notifications on. I can do this by running two instances of the bot, but it'd be much better if we didn't need to do that.

**Comment by Bombg** [comment]
I like the idea and will look into adding it.

**Comment by Bombg** [comment]
You can now set a channel per platform to send online notifications to. Everything is explained in constants.py.
