### ISSUE TITLE
Discord notification role feature request 

### ISSUE THREAD

**Issue by stormerider** [Bombg/SassBot#4]
Right now, the message when a streamer comes online doesn't do a mention like `@everyone`. In our case, we have a notification role for when our streamer goes live like `@Notifications-Rin-Streaming`, so being able to include that in the messages the bot posts would be very helpful. As far as I can see, the only customizable part of the message is on the image description, which won't trigger a notification to the best of my knowledge.

**Comment by Bombg** [comment]
There's a command to turn on @everyone mentions /everyone-ping-toggle true will do it. Although I do like the idea of being able to add specific roles, so I'll look into that. Also you can further customize some of the messages inside the Notifications.py. Such as ofOnlineText, cbOnlineText etc.

**Comment by Bombg** [comment]
You can now ping other roles other than just everyone, and you can set a role per platform if you wish. The everyone-ping-toggle command is just now /ping-toggle. The constants.py file explains how to set this up. Let me know if you have any questions.

**Comment by Bombg** [comment]
I also moved other flavor text that was previously in notifications.py over to constants to more easily edit all of it.

**Comment by stormerider** [comment]
Perfect, thank you very much for the insanely fast turn around time on these FRs! I'll test them out ASAP and report back. Was planning on digging into them myself if I could find the time, but I only got it all running yesterday morning and I only had a chance to test it when Rin started her MFC stream last night.
