### ISSUE TITLE
OnlyFans and Fansly detection

### ISSUE THREAD

**Issue by stormerider** [Bombg/SassBot#5]
I was doing some testing this morning with the new features you added in overnight, and they appear to be working, but I'm not 100% sure on that yet. I was able to get good notifications when I launched Twitch or Kick, and verified the ping toggle works, but I was not able to get notifications for OnlyFans or Fansly (which are the ones I have pointed at the secondary Duscord channels). I have `DEBUG = True` set in Constants.py, but where I would see negative values like this when connected to Twitch or Kick:
```
changed avatar to good Jasmeralia
twitchOffline: -120
kickOffline: 972
onlyfansOffline: 979
fanslyOffline: 980

...

twitchOffline: 1569
kickOffline: 1571
onlyfansOffline: 1579
fanslyOffline: 1581
Updated presence to Offline

...

twitchOffline: 239
kickOffline: -1694271810
kickBoobies
onlyfansOffline: 1819
fanslyOffline: 1821
Updated presence to Kick
```

I never saw the bot detect that I was streaming on either OnlyFans or Fansly, either through a negative number or an `Updated presence` message. However, I'm wondering if this is a config issue rather than a code issue; I know the streaming status on those platforms may not be visible to non-subscribers, where MFC, Twitch, and Kick are all visible to users who aren't logged in. Is there a specific set of permissions/privacy settings that need to be configured on those services so the bot can determine if a stream is active, or is there a section in the bot config to have it authenticate to them before trying to check that I may have missed?

**Comment by Bombg** [comment]
Positive values with the debug means how long the stream has been offline in seconds, and negative numbers is how long the stream has been online in seconds.  Some of the values are defaulted to 0 when generating the database so its gonna throw some wild numbers at first, and the print is made before any database changes are made. thus the large negative number that's close to the current epoch time. 

The stream detection for Onlyfans and Fansly is rather crude. It just uses selenium/chrome and looks to see if they have the live/streaming icon over/near their profile picture. So far I've not had any issues detecting streams with it, but if there is a mode where only subs can see if they're streaming then that would cause issues for sure. If you want to see what selenium is seeing you can take a screenshot by adding this line to checkers/fansly.py and checkers/onlyfans.py
`driver.get_screenshot_as_file("screenshot.png")`

If you do need to be logged in and that is the problem you're having you can log in via the chrome browser and then attach the user profile to selenium. 
`chrome_options.add_argument("user-data-dir=pathTOUserDataDir")`
on windows it's C:\\Users\\PUTYOURWINUSERNAMEHERE\\AppData\\Local\\Google\\Chrome\\User Data but not sure about Linux.

**Comment by stormerider** [comment]
Perfect, that's exactly the info I needed. I have some degree of familiarity with Selenium from my day job (I'm a DevOps manager and the QA folks my team help support use it), so I should be able to get things sorted from here with the excellent pointers you've provided. Thanks again for the incredible response times and a wonderful application. Major kudos!
